### ISSUE TITLE
module STAThelper not found with Python3 installation

### ISSUE THREAD

**Issue by rashawnLK** [LLNL/STAT#13] opened 2019-12-16 23:50 UTC
Hello,
I'm not sure if this is the right place to log this.

I have a recent build of STAT 4.0.1 (cloned from commit 596941a), configured with Python3. When I use 'stat-cl -C srun <application>' ,  I encounter the following error:

`Traceback (most recent call last):
  File "/opt/tools/install/stat-4.0.1-commit-596941/lib/python2.7/site-packages/STATmain.py", line 49, in <module>
    from STAThelper import exec_and_exit
ModuleNotFoundError: No module named 'STAThelper'`

I do not know where this module is. I do not find a Python 3 directory in my installation, but I do have a python 2.7 directory, with site-packages.  I configured the build in this way:

`./configure --prefix=${statinst} --with-boost=${boostinst} --with-python=/usr/bin/python3 \
--with-graphlib=${graphinst} --with-launchmon=${lmoninst} --with-elfutils=${euroot} \
--with-stackwalker=/<pathTo>/dyninst-10.1.0-install/gcc-8.3.0/lib  --with-mrnet=${mrnetroot}  \
--with-mpih=/opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/include/mpi.h  \
--enable-gui=no --enable-examples --enable-shared \
CPPFLAGS=${cppflags} LDFLAGS=${ldflags} 2>&1 | tee  configure.out `

Versions:
Boost @ 1.66.0 
graphlib @ 3.0
Python 3 @ 3.6.5 (default Python 3 on machine)
LaunchMON @ cloned from commit 2691773
Elf Utils @ 1.73 (using version installed as part of the Dyninst build)
MRNet @ 5.0.1 (cloned from commit 7375ba5)
MPI: Intel MPI @ 2019.5.281
Dyninst @ 10.1.0 (uses the same Boost library as STAT)

The configure, make, and 'make install' steps completed without error.

Will you let me know if something stands out as building this incorrectly and/or how I obtain the STAThelper module? 

Best regards,

Rashawn

**Comment by lee218llnl** [comment] 2019-12-23 18:06
@rashawnLK, can you please provide your config.log file? While you specify --with-python=/usr/bin/python3, it appears to be picking up python 2.7 for some reason.

**Comment by rashawnLK** [comment] 2019-12-23 18:32
@lee218llnl, I have attached the config.log file here:
[2019_1216_config.log](https://github.com/LLNL/STAT/files/3995874/2019_1216_config.log)

Thanks,

-Rashawn

**Comment by lee218llnl** [comment] 2019-12-23 18:41
Thanks, I can reproduce this issue. FWIW, a viable workaround may be to specify PYTHON=/usr/bin/python3 on your configure line. I will see if I can fix the configure scripts to actually obey the --with-python arg.

**Comment by lee218llnl** [comment] 2019-12-23 21:34
@rashawnLK can you please see if the latest commit to develop https://github.com/LLNL/STAT/commit/9dd53138befa6a92454bfbdfd174b6ae82dd43f2 fixes the Python configuration. Simply specifying --with-python= should work and you should not have to define PYTHON= anymore.

**Comment by rashawnLK** [comment] 2019-12-27 02:46
@lee218llnl, I did build this, and the I now have two python3.6/site-packages directories: one under <STAT-install>/lib and the other under <STAT-install>/lib64.   In the the lib/python3.6/site-packages there are the following files: 
attach_helper.py  
bg_core_backtrace.py  
core_file_merger.py  
__pycache__  STATmain.py  
stat_merge_base.py  
STATmerge.py 

In the lib64/python3.6/site-packages, there are two files: _STATmerge.la and _STATmerge.so. 

I did not find the STAThelper.py module and obtained the same error when running, "stat-cl -C srun <MPI application>":

`Traceback (most recent call last):
  File "/mnt/lustre/opt/A21-community_tools/install/stat-4.0.1-commit-9dd5313_gcc-7.4.1_impi-2019.5.281/lib/python3.6/site-packages/STATmain.py", line 49, in <module>
    from STAThelper import exec_and_exit
ModuleNotFoundError: No module named 'STAThelper'`

My config.log file is attached.

Thank you,

-Rashawn

[2019_1226_config.log](https://github.com/LLNL/STAT/files/4003932/2019_1226_config.log)

**Comment by lee218llnl** [comment] 2019-12-27 18:19
@rashawnLK, for this one, I would need to see your full `make` and `make install` output. The STAThelper.py should install in the lib/python3.6/site-packages directory if everything worked OK.

**Comment by rashawnLK** [comment] 2019-12-27 18:35
@lee218llnl, Thank you for investigating this. My output make  and make-install files are attached.

Thanks,

-Rashawn

[2019_1226_stat-4.0.1_gcc-7.4.1_make-03.out.txt](https://github.com/LLNL/STAT/files/4006006/2019_1226_stat-4.0.1_gcc-7.4.1_make-03.out.txt)
[2019_1226_stat-4.0.1_gcc-7.4.1_make-install-03.out.txt](https://github.com/LLNL/STAT/files/4006007/2019_1226_stat-4.0.1_gcc-7.4.1_make-install-03.out.txt)

**Comment by lee218llnl** [comment] 2019-12-27 18:46
@rashawnLK. I found that the problem was because you specify --enable-gui=no, but STAT's build system was only installing STAThelper.py when the GUI was enabled. This is a bug in the build system as the helper is now needed even without the GUI. I made the appropriate fix to scripts/Makefile.am. Please pull from the develop branch, run `bootstrap`, then reconfigure and build. Let me know if that works.

**Comment by rashawnLK** [comment] 2019-12-27 19:49
@lee218llnl, It is now working with the pull from the develop branch. Thank you for working on this.

Best regards,

-Rashawn

**Comment by lee218llnl** [comment] 2019-12-27 22:11
No problem, thanks for catching these problems. I will close this issue.

**Closed by lee218llnl** 2019-12-27 22:11 UTC
