### ISSUE TITLE
Spack Unable to install for Mac Mojave/Catalina systems

### ISSUE THREAD

**Issue by matthiaslum** [LLNL/STAT#19] opened 2020-03-24 09:35 UTC
./spack install stat

==> Warning: clang@11.0.0-apple cannot build optimized binaries for "broadwell". Using best target possible: "x86_64"
==> Error: libelf@0.8.13%clang@11.0.0-apple arch=darwin-catalina-x86_64 does not satisfy elf@1

**Comment by lee218llnl** [comment] 2020-03-24 13:08
@matthiaslum I have never tried building on a Mac and don't have access to one to test this. It looks like the problem is the provider of elf. Can you try to `spack install stat^elfutils`?

**Comment by matthiaslum** [comment] 2020-03-24 13:28
It results in "%clang" conflicts with "elfutils".
Is there any other system you would recommend building STAT on?
How about windows?

**Comment by lee218llnl** [comment] 2020-03-24 13:49
Your best bet would be to build STAT on a Linux system if you have access. Windows is definitely not going to work. Something else you may try on your Mac is to install gcc and use that as the compiler. I will also point out that TotalView and DDT are both great parallel debuggers and may offer student discounts (or potentially even free licenses). TotalView and DDT are both full-featured debuggers like GDB. Please note that STAT is primarily designed to debug hangs and doesn't do much other than gather stack traces.

**Comment by pramodk** [comment] 2021-04-09 23:34
@lee218llnl @matthiaslum :  Packages like `Dyninst` are not supported on Mac OS. So I think we should add conflict for darwin platform in Spack recipe and close this issue.

**Comment by lee218llnl** [comment] 2021-04-09 23:38
> @lee218llnl @matthiaslum : Packages like `Dyninst` are not supported on Mac OS. So I think we should add conflict for darwin platform in Spack recipe and close this issue.

I think this is better to report in the Spack github project. Can you submit a PR or issue there?

**Comment by lee218llnl** [comment] 2021-04-09 23:38
I can add the conflict in STAT's Spack package too.

**Comment by pramodk** [comment] 2021-04-10 11:03
Sure. Done!

**Comment by lee218llnl** [comment] 2021-04-12 15:39
STAT was designed for large-scale HPC systems. Mac OS is unfortunately not supported.

**Closed by lee218llnl** 2021-04-12 15:39 UTC
