### ISSUE TITLE
Encounter SDBG_TRACER_ERROR (ERROR) with BACKTRACE when executing stat-cl

### ISSUE THREAD

**Issue by rashawnLK** [LLNL/STAT#21] opened 2020-10-14 00:08 UTC
Hello,

I have a built from source build of STAT 4.0.2 in which I encounter a LaunchMON error,  "SDBG_TRACER_ERROR (ERROR)" and BACKTRACE after the application has completed it work and just before the STAT and launchmon processes should detach from the application. The job hangs, and does not exit properly.

STAT build configuration details:
OS: SLES 15.2
C and C++ compilers: GNU 7.5.0
Dyninst 10.1.0
graphlib-3.0
Boost 1.66
Elfutils 0.178
MRNet 5.0.1
LaunchMON - clone from 29 September 2020
TBB from the 2020.0.166 Intel compilers suite
Python 3.6.10
Graphviz application 2.44.1
Graphviz Python module  0.14.2
MPICH - internal development version 

The resource manager is set as mpiexec.hydra. Both attach_1 and launch_1 tests from LaunchMON run to completion without error.

I specify the job to run on a single node within an sbatch script: stat-cl -a -C  srun -n8 -N1 <application> <application args ...>.
I launch the script with sbatch.

The text of the SDBG_TRACER_ERROR (ERROR) and BACKTRACE  is in the application output file attached, but the text of the error is here:
<Oct 13 14:19:06> <Launchmon> (INFO): The RM process has just been forked and exec'ed.
<Oct 13 14:19:06> SDBG_TRACER_ERROR (ERROR): [filename: sdbg_linux_ptracer.hxx, linenum: 95] [linux_ptracer_t::tracer_read] error returned from ptrace Input/output error
<Oct 13 14:19:06> SDBG_TRACER_ERROR (ERROR): BACKTRACE: 
launchmon: linux_tracer_exception_t::linux_tracer_exception_t(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tracer_error_e)
launchmon: linux_ptracer_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>::tracer_read(process_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&, unsigned long, void*, int, bool)
launchmon: linux_ptracer_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>::enable_breakpoint(process_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&, breakpoint_base_t<unsigned long, unsigned long>&, bool, bool)
launchmon: linux_launchmon_t::handle_mpir_variables(process_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&, image_base_t<unsigned long, elf_wrapper>&)
launchmon: linux_launchmon_t::handle_trap_after_exec_event(process_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&)
launchmon: launchmon_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>::invoke_handler(process_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&, launchmon_event_e, int)
launchmon: event_manager_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>::poll_processes(process_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&, launchmon_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&)
launchmon: event_manager_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>::multiplex_events(process_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&, launchmon_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>&)
launchmon: driver_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>::drive_engine(opts_args_t*)
launchmon: driver_base_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct, my_thrinfo_t, elf_wrapper>::drive(int, char**)
launchmon: linux_driver_t<unsigned long, unsigned long, unsigned long, user_regs_struct, user_fpregs_struct>::driver_main(int, char**)
launchmon: main
libc.so.6: __libc_start_main
launchmon: _start

Any pointers towards ways to resolve this will be appreciated.

Thank you,

-Rashawn

[2020_1013_stat_amg2013_gcc-7.5.0_mpichGNUdrop36_01N-02t-8ppn_188383_c002n0024-0.out.txt](https://github.com/LLNL/STAT/files/5374743/2020_1013_stat_amg2013_gcc-7.5.0_mpichGNUdrop36_01N-02t-8ppn_188383_c002n0024-0.out.txt)

**Comment by lee218llnl** [comment] 2020-10-15 18:03
It looks like the application completed before STAT was able to get fully attached, so errors are not entirely unexpected. Why are you trying to launch and run this under STAT? Does the application actually hang? If so, could you try attaching to the job rather than launching it with STAT?

**Comment by lee218llnl** [comment] 2020-10-26 18:00
@rashawnLK any updates on this? Did you see my previous comment?

**Comment by rashawnLK** [comment] 2020-10-26 19:26
@lee218llnl, Thank you for asking about attaching to the process.  I thought I could use STAT on an application that is not hanging to show that STAT is working.  I changed my approach to attach explicitly to the running STAT examples. This is working. I delayed in responding because of a separate internal issue with dependencies which were in an earlier environment but are now missing and affect how the GUI displays. I wanted to make sure it is all working as it should. It is okay to close this issue.

**Comment by lee218llnl** [comment] 2020-10-26 20:32
@rashawnLK You certainly can attach to an application that is running OK to make sure it works. Also, launching a job under STAT should be fine too. I think the problem is that the AMG benchmark runs to completion too fast for STAT to have time to attach. I haven't run the AMG benchmark in a while, but recall with the default parameters that it is a very short run. I also don't remember if you can specify problem/run parameters such that it takes longer to run. You may want to consider trying again on a longer running AMG job or on a different application that takes longer to complete.

I will close this issue for now, but feel free to reopen it if you get a chance to try on a longer running application and if you still see issues. You can also open a new issue if there's something w.r.t. the GUI That you need help looking at.

**Closed by lee218llnl** 2020-10-26 20:32 UTC
